    ;
    ; platformio.ini
    ;

    [env:esp32-s3]
    platform = espressif32
    board = esp32-s3-devkitc-1
    framework = arduino
    monitor_speed = 115200
    upload_port = 
    monitor_port = 

    lib_deps =
        zinggjm/GxEPD2
        adafruit/Adafruit GFX Library
        adafruit/Adafruit BusIO
        fbiego/ESP32Time